document.write('<div class="separator" style="clear: both; text-align: left;">');
document.write('    <figure>'  );
document.write('      <a target="_blank"href="https://kensbookinfo.blogspot.com/p/support-this-website.html"style="margin-left: 1em; margin-right: 1em;">');
document.write('        <img border="0" data-original-height="853" data-original-width="1280" height="90" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiOPLW2ZlJs9lPtfgY6Va_LXdodrwaH8rfpdgT9V47cCWRmhDp8Q3T7DTFaGz0VDifyrfak97IiiAmKsohcV_jIfBS4YiendDunTz-pQEmx8FBOAwa8LJmbhVqqKQaK6ISeox0LhRuLjyZr_mLkK-ByEZoG_3FC0QGesXvZKLfIBOYqbyGUywS8bgT0uwk/s320/Contribute.png" width="90" />');
document.write('        <br />The site is free to use, but it is not without cost. If you find it useful we would appreciate your support by clicking this link and making a contribution to our cause. Thank you!</a>');
document.write('    </figure>');
document.write('  </div>');
document.write('<br />Share <a target="_blank"href="https://www.facebook.com/sharer.php?u=https%3A%2F%2Fkensbookinfo.blogspot.com%2Fp%2Fhome_5.html%3Fspref%3Dfb&t=Ken%27s%20Blogspot%3A%20HOME">');
document.write('  <button type="button"style="background-color: #4267B2; color: #ffffff; font-weight: bold; width:75px;">facebook</button>');
document.write('</a>');
document.write('<a target="_blank"href="https://twitter.com/intent/tweet?url=https://kensbookinfo.blogspot.com/p/home_5.html?spref%3Dtw&text=Ken%27s+Blogspot:+HOME">');
document.write('  <button type="button"style="background-color: #000000; color: #ffffff; font-weight: bold; width:75px;">X</button>');
document.write('</a>');
document.write('<a target="_blank"href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fwww.linkedin.com">');
document.write('  <button type="button"style="background-color: #0077B5; color: #ffffff; font-weight: bold; width:75px;">LinkedIn</button>');
document.write('</a>');
document.write('<a target="_blank"href="https://www.tumblr.com/widgets/share/tool?posttype=link&title=Ken%27s%20Blogspot%3A%20test&caption=An%20aging%20Mr.%20Smith%20is%20a%20complex%20person%2C&content=https%3A%2F%2Fkensbookinfo.blogspot.com%2Fp%2Ftest.html&canonicalUrl=https%3A%2F%2Fkensbookinfo.blogspot.com%2Fp%2Ftest.html&shareSource=tumblr_share_button">');
document.write('  <button type="button"style="background-color: #33465D; color: #ffffff; font-weight: bold; width:75px;">tumblr</button>');
document.write('</a>');
document.write('<a target="_blank"href="https://www.threads.net/intent/post?url=https://kensbookinfo.blogspot.com/p/home_5.html?spref%3Dtw&text=Ken%27s+Blogspot:+HOME">');
document.write('  <button type="button"style="background-color: #000000; color: #ffffff; font-weight: bold; width:75px;">threads</button>');
document.write('</a>');
document.write('<a target="_blank"href="https://www.pinterest.com/pin-builder/?description=Ken%27s+Blogspot%3A+HOME&media=https%3A%2F%2Fblogger.googleusercontent.com%2Fimg%2Fb%2FR29vZ2xl%2FAVvXsEjOkVXNsRp4Vg_Qgp3Wapeun1gqnKyMerI6PxzGJXbdOwfanXPKkEMPnz0HcHKWNvPw1btO_4jC53aK6lBcSuj5UjA8if6BPJbEigtOzB-473LkRDQNHvJTM7_IBe4Jit7wh0BvMN5aA65QUGCyuEWZy5nPLFgGMB3DNP_B-4ZrvtRk7g%2Fs1600%2FKen%27s%2520Books%252020210426.jpg&method=button&url=https%3A%2F%2Fkensbookinfo.blogspot.com%2Fp%2Fhome_5.html%3Fspref%3Dpi">');
document.write('  <button type="button"style="background-color: #E60023; color: #ffffff; font-weight: bold; width:75px;">pinterest</button>');
document.write('</a>');
document.write('<a target="_blank"href="https://www.blogger.com/blog-this.g?u=https://kensbookinfo.blogspot.com/p/home_5.html?spref%3Dbl&n=Ken%27s+Blogspot:+HOME&t=+++++The+site+is+free+to+use,+but+it+is+not+without+cost.+');
document.write('If+you+find+it+useful+please+consider+a+contribution+and+click+this+link.">');
document.write('  <button type="button"style="background-color: #fc4f08; color: #ffffff; font-weight: bold; width:75px;">blogger</button>');
document.write('</a>');
document.write('');
